dons_index:
    path:     /
    defaults: { _controller: "DonationBundle:Dons:index" }
    methods:  GET

dons_show:
    path:     /{id}/show
    defaults: { _controller: "DonationBundle:Dons:show" }
    methods:  GET
    
dons_mine:
    path:     /mesdons
    defaults: { _controller: "DonationBundle:Dons:mine" }
    methods:  GET

dons_new:
    path:     /new
    defaults: { _controller: "DonationBundle:Dons:new" }
    methods:  [GET, POST]

dons_edit:
    path:     /{id}/edit
    defaults: { _controller: "DonationBundle:Dons:edit" }
    methods:  [GET, POST]

dons_delete:
    path:     /{id}/delete
    defaults: { _controller: "DonationBundle:Dons:delete" }
    methods:  DELETE
